// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW7jwexX2eu1pTjUKEY6bhCkJ37gKkWCQ',
    appId: '1:170115049499:web:05a155a00e138d30f9b0be',
    messagingSenderId: '170115049499',
    projectId: 'mynotes-modrzywolek',
    authDomain: 'mynotes-modrzywolek.firebaseapp.com',
    storageBucket: 'mynotes-modrzywolek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3uN1eUGp-qhxLAsobbRDha7ulb_wk3Q',
    appId: '1:170115049499:ios:ca2ad251fda0ba36f9b0be',
    messagingSenderId: '170115049499',
    projectId: 'mynotes-modrzywolek',
    storageBucket: 'mynotes-modrzywolek.appspot.com',
    iosBundleId: 'com.modrzywolek.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi3uN1eUGp-qhxLAsobbRDha7ulb_wk3Q',
    appId: '1:170115049499:ios:ca2ad251fda0ba36f9b0be',
    messagingSenderId: '170115049499',
    projectId: 'mynotes-modrzywolek',
    storageBucket: 'mynotes-modrzywolek.appspot.com',
    iosBundleId: 'com.modrzywolek.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW7jwexX2eu1pTjUKEY6bhCkJ37gKkWCQ',
    appId: '1:170115049499:web:0605d4629a07f013f9b0be',
    messagingSenderId: '170115049499',
    projectId: 'mynotes-modrzywolek',
    authDomain: 'mynotes-modrzywolek.firebaseapp.com',
    storageBucket: 'mynotes-modrzywolek.appspot.com',
  );
}
